apiVersion: v1
kind: Service
metadata:
  name: servicio-python
spec:
  type: NodePort
  selector:
    app: app-python
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-1
        image: rigiba/devops
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-node
spec:
  type: NodePort
  selector:
    app: app-node
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
      - name: app-node
        image: rigiba/devnodeapp
        ports:
        - containerPort: 5173
